# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on: push
name: Linux
jobs:
  verify:
    name: Verify
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        nodejs:
        - 12
      fail-fast: false
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}
    - name: Output versions
      run: |
        node -v
        npm -v
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Verify
      run: npm run verify
